- name: mongodb database
  become: yes
  hosts: mongodb
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: vim /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
      
  - name: start mongodb
    ansible.builtin.service:
      name: start service
      state: start
      enabled: yes
