- name: Installing nginx
  hosts: frontend
  become: yes
  connection: ssh
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
        
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes