- name: fetch variables from file
  hosts: frontend
  var_files:
    course.yaml
  tasks:
    ansible.builtin.debug:
      msg: "I'm learning {{course}} with {{educator}} and it has {{duration}} for 4 months"